title: Nicole Vasquez
#logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal

email: nicole.tiare.vasquez@gmail.com
search: true

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: neon

site:
  locale: "en-US"
#  description: "DungenRobot's funtastic blog"

#https://fontawesome.com/icons
#https://fontawesome.com/v4/icons/
#https://fontawesome.cc
footer:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      email: "nicole.tiare.vasquez@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nicoletiarev"
    
    #- label: "YouTube"
    # icon: "fab fa-youtube"
    #  url: "https://youtube.com/@dungenrobot"
    #- label: "Discord"
    #  icon: "fab fa-discord"
    #  url: "https://discord.gg/YUECSUHHM8"

#plugins:
#  - jekyll-include-cache 
#  - jekyll-feed

#defaults:
#    #_posts
# - scope:
#     type: posts
#   values:
#     layout: single
#     show_date: true
#     author_profile: false
#     read_time: false
#      comments: true
#      share: false
#      related: false

#c:\Ruby32-x64\lib\ruby\gems\3.2.0\gems\minimal-mistakes-jekyll-4.24.0
#markdown: kramdown
#highlighter: rouge


